{
    'name': 'Hello World Website',
    'version': '1.0.0',
    'author': 'Your Name',
    'description': 'My custom website for Odoo',
    'category': 'Website',
    'depends': ['website', 'snippets_library'],
    'data': [
        'views/head.xml',
        'views/snippets/helpers/s_dialog_form.xml',
        'views/snippets/helpers/s_contact_us_section.xml',
        'views/snippets/helpers/s_contact_modal.xml',
        
        'views/snippets/homepage/s_homepage_first_section.xml',
        'views/snippets/homepage/s_homepage_second_section.xml',
        'views/snippets/homepage/s_homepage_third_section.xml',
        'views/snippets/homepage/s_homepage_fourth_section.xml',
        'views/snippets/homepage/s_homepage_fifth_section.xml',
        'views/snippets/homepage/s_homepage_sixth_section.xml',
        'views/snippets/homepage/s_homepage_seventh_section.xml',
        'views/snippets/homepage/s_homepage_eighth_section.xml',
        'views/snippets/homepage/s_homepage_nineth_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_first_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_second_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_third_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_fourth_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_fifth_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_sixth_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_seventh_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_eighth_section.xml',
        
        'views/homepage.xml',
        'views/aboutUsPage.xml',
        'views/about_odoo_page.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'helloworld_module/static/src/scss/theme_style.scss',
            # 'helloworld_module/static/src/scss/style.scss',
            # 'helloworld_module/static/src/scss/accordion_style.scss',
            # 'helloworld_module/static/src/js/accordion.js',
            'helloworld_module/static/src/scss/_variables.scss',
            'helloworld_module/static/src/scss/_mixins.scss',
            'helloworld_module/static/src/scss/mainpage.scss',
            'helloworld_module/static/src/scss/about_odoo_page.scss',
            'helloworld_module/static/src/scss/contact_us_section.scss',
            'helloworld_module/static/src/scss/dialog_modal_form.scss',
            'helloworld_module/static/src/scss/index.scss',
            # 'helloworld_module/static/src/js/mainpage.js',
        ],
        'web._assets_frontend_helpers': [
            ('prepend', 'helloworld_module/static/src/scss/bootstrap_overridden.scss'),
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}