{
    'name': 'Hello World Website',
    'version': '1.0.0',
    'author': 'Your Name',
    'description': 'My custom website for Odoo',
    'category': 'Website',
    'depends': ['website', 'crm'],
    'data': [
        'views/head.xml',
        'views/snippets/helpers/s_dialog_form.xml',
        'views/snippets/helpers/s_contact_us_section.xml',
        'views/snippets/helpers/s_contact_modal.xml',
        'views/snippets/helpers/s_callback_modal.xml',
                
        'views/snippets/homepage/s_homepage_first_section.xml',
        'views/snippets/homepage/s_homepage_second_section.xml',
        'views/snippets/homepage/s_homepage_third_section.xml',
        'views/snippets/homepage/s_homepage_fourth_section.xml',
        'views/snippets/homepage/s_homepage_fifth_section.xml',
        'views/snippets/homepage/s_homepage_sixth_section.xml',
        'views/snippets/homepage/s_homepage_seventh_section.xml',
        'views/snippets/homepage/s_homepage_eighth_section.xml',
        'views/snippets/homepage/s_homepage_nineth_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_first_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_second_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_third_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_fourth_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_fifth_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_sixth_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_seventh_section.xml',
        'views/snippets/about_odoo_page/s_about_odoo_page_eighth_section.xml',
        'views/snippets/modules_page/s_modules_page_first_section.xml',
        'views/snippets/modules_page/s_modules_page_second_section.xml',
        'views/snippets/modules_page/s_modules_page_third_section.xml',
        'views/snippets/contacts_page/s_contacts_first_section.xml',
        'views/snippets/contacts_page/s_contacts_second_section.xml',
        'views/snippets/contacts_page/s_contacts_third_section.xml',
        'views/snippets/contacts_page/s_contacts_fourth_section.xml',
        'views/snippets/contacts_page/s_contacts_fifth_section.xml',
        'views/snippets/contacts_page/s_contacts_sixth_section.xml',
        'views/snippets/contacts_page/s_contacts_seventh_section.xml',
        'views/snippets/contacts_page/s_contacts_eighth_section.xml',
        'views/snippets/contacts_page/s_contacts_ninth_section.xml',
        'views/snippets/contacts_page/s_contacts_tenth_section.xml',
        'views/snippets/contacts_page/s_contacts_eleventh_section.xml',
        'views/snippets/contacts_page/s_contacts_twelfth_section.xml',
        
        'views/homepage.xml',
        'views/about_odoo_page.xml',
        'views/modules_page.xml',
        'views/contacts_page.xml',

        'data/website_data.xml',
        'data/menu_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'helloworld_module/static/src/scss/helpers/theme_style.scss',
            'helloworld_module/static/src/scss/helpers/_variables.scss',
            'helloworld_module/static/src/scss/helpers/_mixins.scss',
            'helloworld_module/static/src/scss/header-footer.scss',
            'helloworld_module/static/src/scss/helpers/contact_us_section.scss',
            'helloworld_module/static/src/scss/helpers/dialog_modal_form.scss',
            'helloworld_module/static/src/scss/index.scss',
            'helloworld_module/static/src/scss/mainpage.scss',
            'helloworld_module/static/src/scss/about_odoo_page.scss',
            'helloworld_module/static/src/scss/modules_page.scss',
            'helloworld_module/static/src/scss/contacts_page.scss',
        ],
        'web._assets_frontend_helpers': [
            ('prepend', 'helloworld_module/static/src/scss/helpers/bootstrap_overridden.scss'),
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}